name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: podma-bd-cp1.hostever.com
          username: hostel_payments_server@pay-hostel-server.rpi.gov.bd	
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
